---
title: "Global COVID-19 Dashboard"
author: "Alexander Bates"
output:
    flexdashboard::flex_dashboard:
      orientation: rows
      theme: cosmo
runtime: shiny
---

# Loading the libraries
```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(ggplot2)
library(tidyr)
library(tidyverse)
library(dplyr)
library(leaflet)
library(maps)
library(plotly)
```

# Reading, cleaning, and transforming the data
```{r data}
cases_raw <- read_csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv")
deaths_raw <- read_csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv")
recovs_raw <- read_csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv")



tidy_function <- function(data, start_col = 5, values_to = "x") {
  data %>%
    pivot_longer(start_col:last_col(),
               names_to = "date",
               values_to = values_to) %>%
    mutate(date = as.Date(date, "%m/%d/%y")) %>%
    rename(Country = `Country/Region`)
  }


cases_tidy <- cases_raw %>% tidy_function(5, "Count")
deaths_tidy <- deaths_raw %>% tidy_function(5, "Count")
recovs_tidy <- recovs_raw %>% tidy_function(5, "Count")

```
# Constructing the sidebar
Inputs {.sidebar}
-----------------------------------------------------------------------
```{r}
selectInput("data_type",
            "Select Data Type: ",
            choices = c('Cases', 'Deaths', 'Recoveries'),
            selected = "Cases")

### Region of Interest
selectInput(inputId = "country",
               label = "Choose country: ",
               choices = c('Afghanistan',
                           'Albania',
                           'Argentina',
                           'Australia',
                           'Austria',
                           'Bangladesh',
                           'Barbados',
                           'Belgium',
                           'Bolivia',
                           'Botswana',
                           'Brazil',
                           'Brunei',
                           'Bulgaria',
                           'Burkina Faso',
                           'Burma',
                           'Burundi',
                           'Cabo Verde',
                           'Canada',
                           'Cambodia',
                           'Cameroon',
                           'Central African Republic',
                           'Chad',
                           'Chile',
                           'China',
                           'Costa Rica',
                           'Croatia',
                           'Cuba',
                           'Denmark',
                           'Domican Republic',
                           'Ecuador',
                           'Egypt',
                           'El Salvador',
                           'France',
                           'Germany',
                           'Greece',
                           'Guatemala',
                           'Haiti',
                           'Iceland',
                           'Ireland',
                           'Israel',
                           'Italy',
                           'Japan',
                           'Jamaica',
                           'Kenya',
                           'Kiribati',
                           'Korea, South',
                           'Kosovo',
                           'Kuwait',
                           'Krygyzstan',
                           'Laos',
                           'Latvia',
                           'Lebanon',
                           'Lesotho',
                           'Liberia',
                           'Libya',
                           'Liechtenstein',
                           'Lithuania',
                           'Luxembourg',
                           'MS Zaandam',
                           'Madagascar',
                           'Malaysia',
                           'Maldives',
                           'Mali',
                           'Malta',
                           'Marshall Islands',
                           'Mauritania',
                           'Mauritius',
                           'Mexico',
                           'Micronesia',
                           'Maldova',
                           'Monaco',
                           'Mongolia',
                           'Montenegro',
                           'Morocco',
                           'Mozambique',
                           'Namibia',
                           'Nepal',
                           'Netherlands',
                           'New Zealand',
                           'Nicaragua',
                           'Niger',
                           'Nigeria',
                           'North Macedonia',
                           'Norway',
                           'Oman',
                           'Pakistan',
                           'Palau',
                           'Panama',
                           'Papau New Guinea',
                           'Paraguay',
                           'Peru',
                           'Philippines',
                           'Poland',
                           'Portugal',
                           'Qatar',
                           'Romania',
                           'Russia',
                           'Rwanda',
                           'Saint Kitts and Nevis',
                           'Saint Lucia',
                           'Saint Vincent and the Grenadines',
                           'Samoa',
                           'San Marino',
                           'Sao Tome and Principe',
                           'Saudi Arabia',
                           'Senegal',
                           'Serbia',
                           'Seychelles',
                           'Sierre Leone',
                           'Singapore',
                           'Slovakia',
                           'Slovenia',
                           'Somalia',
                           'South Africa',
                           'South Sudan',
                           'Spain',
                           'Sri Lanka',
                           'Sudan',
                           'Sweden',
                           'Switzerland',
                           'Syria',
                           'Taiwan',
                           'Tajikistan',
                           'Tanzania',
                           'Thailand',
                           'Timor-Leste',
                           'Togo',
                           'Trinidad and Tobago',
                           'Tunisia',
                           'Turkey',
                           'Uganda',
                           'US',
                           'Ukraine',
                           'United Arab Emirates',
                           'United Kingdom',
                           'Uruguay',
                           'Uzbekistan',
                           'Vanuatu',
                           'Venezuela',
                           'Vietnam',
                           'West Bank and Gaza',
                           'Yemen',
                           'Zambia',
                           'Zimbabwe'),
               selected = c('Germany', 'Italy'),
               multiple = TRUE)
               
               



selectInput(inputId = "case",
            label = "Select by start date or first case: ",
            choices = c("Start Date", "First Case"),
            selected = "First Case" )

selectInput(inputId = "scale",
              label = "Select raw or natural log scale: ",
              choices = c('Raw Scale',
                          'Natural Log'),
              selected = 'Raw Scale')

selectInput(inputId = "time_series",
              label = "Select smoothed or raw time-series plot: ",
              choices = c('Raw Plot',
                          'Smoothed Plot'),
              selected = 'Smoothed Plot')
```

Welcome to my Global COVID-19 Time Series Dashboard. The raw data was gathered from the Johns Hopkins CSSE and has been updated as of 08/18/21. Over 140 countries are included in this dashboard, and you can select one or multiple.

If you hover over the virus map icon, you can see the total count based upon your
selection of cases, deaths, or recoveries. 

On the plot, you can use your cursor
to see the total case, death, or recovery count at a chosen point in time.

Row
--------------------------------------------------------------------------

# Rendering the leaflet plot
```{r}
renderLeaflet({
  
    if (input$data_type == 'Cases' ){
        dat <- cases_tidy
    } else if (input$data_type == 'Deaths'){
        dat <- deaths_tidy
    } else {
        dat <- recovs_tidy
    }
  
  final_dat <- dat[dat$Country == input$country, ]
   
    leaf_map <- final_dat %>%
      filter(Country == input$country)
    
  
    leaficon <- makeIcon(iconUrl = "https://img.icons8.com/ios/452/coronavirus--v1.png", iconWidth = 35, iconHeight = 35)
    
    map <- leaflet(leaf_map) %>% 
      addTiles() %>%
      addMarkers(~Long, ~Lat, popup = ~as.character(Count), label = ~as.character(Count), icon = leaficon)
      
    # addCircleMarkers(~Long, ~Lat, color = "dodgerblue", weight = 2, radius=10, stroke = TRUE, opacity = 0.4, fill = TRUE, fillOpacity = 0.1, fillColor = "aliceblue", popup = ~as.character(Count), label = ~as.character(Count))
    map
})

```

Row {.tabset}
-----------------------------------------------------------------------
# Constructing the interactive plot
```{r}
renderPlotly({
    if (input$data_type == 'Cases' ){
        dat <- cases_tidy
    } else if (input$data_type == 'Deaths'){
        dat <- deaths_tidy
    } else {
        dat <- recovs_tidy
    }
final_dat <- dat[dat$Country == input$country, ]

if(input$case == "First Case") {
    final_dat <- final_dat %>% filter(Count != 0)
} else {
    final_dat
    }

base_plot <- final_dat %>% ggplot(aes(x = date, y = Count, fill = Country)) +  geom_col() +
    geom_point(size = .1) +
    scale_x_date(date_breaks = "1 month", date_labels = "%m-%y") +
    theme_light() 

   if(input$scale == "Natural Log") {
    base_plot <- base_plot + scale_y_continuous(trans = "log")
    base_plot
  } else {
    base_plot
  }
 
 
  if (input$time_series == "Smoothed Plot" ) {
    base_plot <- base_plot + geom_smooth(aes(color = Country))
    base_plot
    } else {
    base_plot
    }
      

ggplotly(base_plot)

})

```









